package system;

public enum SystemEnum {
	ARTILLERY_BEAM, BACKUP_BATTERY, CLOAKING, CLONEBAY, DOORS, DRONES, ENGINES,
	FLAK_ARTILLERY, HACKING, MEDBAY, MIND_CONTROL, OXYGEN, PILOTING, SENSORS, SHIELDS,
	TELEPORTER, WEAPONS
}
